CREATE TABLE MANUFACTURER(
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
);
CREATE TABLE BOTTLE(
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    VOLUME VARCHAR (50),
    MANUFACTURER_ID BIGINT,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER(ID)
);

CREATE TABLE TUBE(
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    MANUFACTURER_ID BIGINT,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER(ID)
);

CREATE TABLE HOOKAH(
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PRICE FLOAT,
    BOTTLE_ID BIGINT NOT NULL,
    TUBE_ID  BIGINT NOT NULL,
    MANUFACTURER_ID BIGINT,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER(ID),
    FOREIGN KEY (BOTTLE_ID) REFERENCES BOTTLE(ID),
    FOREIGN KEY (TUBE_ID) REFERENCES TUBE(ID),
);


